site_name: SuperDuperPython
nav:
  - 'SuperDuperPython': index.md
  - 'Установка': install.md
  - 'Конфигурация': configuration.md
  - 'Использование': usage.md
  - 'API справочник': api.md
theme:
#  name: readthedocs
  name: material
  palette:
    scheme: default     # slate
    primary: teal       # indigo
    language: ru
  features:
    - navigation.indexes: false 
  highlightjs: true
  locale: en
plugins:
  - search:
      lang: ['en']
#  - with-pdf:
#      author: akhud78
  - autorefs
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
  - offline

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
