site_name: SuperDuperPython
nav:
  - 'SuperDuperPython': index.md
  - 'Установка': install.md
  - 'Конфигурация': configuration.md
  - 'Использование': usage.md
  - 'API справочник': api.md
theme:
  name: readthedocs
  highlightjs: true
  locale: ru
plugins:
  - search:
      lang: ['en']
  - autorefs
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
